version: '3.8'
services:
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
  app:
    image: dotnet-app
    build:
      context: .
      dockerfile: dockerFile.yml
    ports:
      - '5000:80'
      - '5001:443'
    depends_on:
      - redis

